---
title: "ForGraeme"
author: "April Wright"
date: "8/26/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Run this:

```{r}
custom_treespace <- function (chains, n.points = 100, burnin = 0, fill.color = NA)
{
  chains = check.chains(chains)
  labels = names(chains)
  ptable = combine.ptables(chains, burnin = 0)
  if (!is.na(fill.color)) {
    if (fill.color %in% names(ptable)) {
    }
    else stop(sprintf("The fill.color name you supplied ('%s') wasn't found in your parameter table",
                      fill.color))
  }
  chain = chains[[1]]
  step = as.integer((length(chain$trees) - burnin)/n.points)
  indices = seq(from = burnin + 1, to = length(chain$trees),
                by = step)
  indices = c(indices, range(length(chain$trees) -5, length(chain$trees)))

  trees = lapply(chains, function(x) x[["trees"]][indices])
  additional = unlist(lapply(length(chain$trees) * (0:(length(chains) -
                                                         1)), function(x) rep(x, length(indices))))
  ptable = ptable[(indices + additional), ]
  dimensions = 2
  alltrees = trees[[1]]
  if (length(trees) > 1) {
    for (i in 2:length(trees)) {
      alltrees = c(alltrees, trees[[i]])
    }
  }
  d <- tree.dist.matrix(alltrees)
  if (sum(d) == 0) {
    x <- rep(0, length(alltrees))
    y <- rep(0, length(alltrees))
    mds <- data.frame(x = x, y = y)
  }
  else {
    mds <- cmdscale(d, k = dimensions)
  }
  points <- as.data.frame(mds)
  row.names(points) <- seq(nrow(points))
  names(points) <- c("x", "y")
  points$chain = ptable$chain
  points$sample = ptable$sample
  points$generation = ptable$generation
  points$bayes = ptable$Bayes
  points$MIG = ptable$MIG

  if (!is.na(fill.color))
    points[, fill.color] = as.numeric(ptable[[fill.color]])
  return(points)
}
```

Then This:
```{r pressure, echo=FALSE}
library(tools)
library(ggplot2)

custom_plots <- function (CombinedTrees, StratFile) {
  rwty_obj <- rwty::load.trees(file = CombinedTrees, logfile = StratFile, skip = 0)  
  points = custom_treespace(rwty_obj, 5000)
  pp <- ggplot(points, aes(x = x, y = y, color = points$MIG))
  final <- pp + geom_point(aes(size=bayes)) + scale_size(range = c(5,1)) + guides(size = guide_legend(reverse=TRUE)) + scale_colour_gradient(low = "blue", high = "yellow")
  just_file <- file_path_sans_ext(CombinedTrees)
  new_filename <- gsub("CombinedTrees", "TreeSpacePlots", paste0(just_file, '.pdf'))
  ggsave(new_filename, final)
}
```
This is my function to make the tip labels between the parsimony trees and the Bayesian trees congruent. I borrowed heavily from your code, obivously.

```{r}
congruify <- function (AgeFilePath, ParsimonyTreePath, BayesianTreesPath, NEXUSPath) {
  ParsimonyTrees <- ape::read.tree(ParsimonyTreePath)
  RawAges <- read.table(AgeFilePath, header = TRUE, stringsAsFactors = FALSE)
  TipAges <- do.call(rbind, lapply(as.list(unique(RawAges[, "Taxon"])), function(x) {y <- unique(apply(RawAges[RawAges[, "Taxon"] == x, c("MaxMa", "MinMa"), drop = FALSE], 1, paste, collapse = "-")); y <- do.call(rbind, strsplit(y, "-")); LAD <- max(as.numeric(y[, 2])); FADs <- as.numeric(y[, 1]); FAD <- min(FADs[FADs >= LAD]); c(FAD, LAD)}))
  rownames(TipAges) <- unique(RawAges[, "Taxon"])
  if(class(ParsimonyTrees) == "phylo") {
    # Form into list:
    ParsimonyTrees <- list(ParsimonyTrees)
    class(ParsimonyTrees) <- "multiPhylo"
  }
  if(length(setdiff(sort(rownames(TipAges)), sort(ParsimonyTrees[[1]]$tip.label))) > 0) {
    NameMatches <- do.call(rbind, lapply(apply(cbind(sort(rownames(TipAges)), sort(ParsimonyTrees[[1]]$tip.label)), 1, as.list), function(x) unlist(x)))
    NameMatches <- NameMatches[NameMatches[, 1] != NameMatches [, 2], , drop = FALSE]
  }
  # For each non-matching name:
  for(j in 1:nrow(NameMatches)) ParsimonyTrees <- lapply(ParsimonyTrees, function(x) {x$tip.label[x$tip.label == NameMatches[j, 2]] <- NameMatches[j, 1]; x})
  # Ensure list is still a multiphylo object:
  class(ParsimonyTrees) <- "multiPhylo"
  RevBayesOutput <- read.table(BayesianTreesPath, header = TRUE, stringsAsFactors = FALSE)
  BayesianTrees <- ape::read.tree(text = RevBayesOutput[, "tree"])
  BayesianTrees <- lapply(BayesianTrees, function(x) {x$edge.length <- NULL; x})
  class(BayesianTrees) <- "multiPhylo"
  OutgroupTaxon <- rownames(Claddis::ReadMorphNexus(NEXUSPath)$Matrix_1$Matrix)[1]
  BayesianTrees <- ape::root(BayesianTrees, outgroup = OutgroupTaxon)
  BayesianTrees <- ape::read.tree(text = unlist(lapply(BayesianTrees, function(x) paste("(", OutgroupTaxon, ",", gsub(";", ");", ape::write.tree(drop.tip(x, tip = OutgroupTaxon))), sep = ""))))
  class(ParsimonyTrees) <- "multiPhylo"
  class(BayesianTrees) <- "multiPhylo"
  new_trees <- c(BayesianTrees, ParsimonyTrees)
  class(new_trees) <- "multiPhylo"
  new_filename <- gsub("RevBayesOutput", "CombinedTrees", gsub(".trees", "", BayesianTreesPath))
  ape::write.nexus(new_trees, file = new_filename)
}
```

```{r}
library(rwty)
library(dplyr)
#Make the list of strat files
files <- list.files(path="Data/StratCongruenceResults/InputTreeResults", pattern="*.txt", full.names=TRUE, recursive=FALSE)
#And the list of treefiles
tre_files <- list.files(path="Data/RevBayesOutput", pattern="*.tre", full.names=TRUE, recursive=FALSE)
mat_files <- list.files(path="Data/NEXUS", pattern="*.nex", full.names=TRUE, recursive=FALSE)
parsimony_files <- list.files(path="Data/MPTs", pattern="*.tre", full.names=TRUE, recursive=FALSE)
ages_files <- list.files(path="Data/Ages", pattern="*.txt", full.names=TRUE, recursive=FALSE)
uniquefilenames <- gsub(".nex.trees", "", unlist(lapply(as.list(tre_files), function(x) strsplit(x, "/")[[1]][3])))
mat_files <- unlist(lapply(as.list(uniquefilenames), function(x) mat_files[grep(x, mat_files)]))
parsimony_files <- unlist(lapply(as.list(uniquefilenames), function(x) parsimony_files[grep(x, parsimony_files)]))
ages_files <- unlist(lapply(as.list(uniquefilenames), function(x) ages_files[grep(x, ages_files)]))
combined_trees <- list.files(path="Data/CombinedTrees", pattern="*.nex", full.names=TRUE, recursive=FALSE)
#Now make the plots
mapply(congruify, ages_files, parsimony_files, tre_files, mat_files)
mapply(custom_plots, combined_trees, files)
```
